sudo apt-get install php7.2-bcmath -y
sudo apt-get install php7.2-bz2 -y
sudo apt-get install php7.2-calendar -y
sudo apt-get install php7.2-ctype -y
sudo apt-get install php7.2-curl -y
sudo apt-get install php7.2-dom -y
sudo apt-get install php7.2-enchant -y
sudo apt-get install php7.2-exif -y
sudo apt-get install php7.2-fileinfo -y
sudo apt-get install php7.2-ftp -y
sudo apt-get install php7.2-gd -y
sudo apt-get install php7.2-gettext -y
sudo apt-get install php7.2-gmp -y
sudo apt-get install php7.2-iconv -y
sudo apt-get install php7.2-intl -y
sudo apt-get install php7.2-json -y
sudo apt-get install php7.2-ldap -y
sudo apt-get install php7.2-mbstring -y
sudo apt-get install php7.2-mysqli -y
sudo apt-get install php7.2-mysqlnd -y
sudo apt-get install php7.2-opcache -y
sudo apt-get install php7.2-pdo -y
sudo apt-get install php7.2-phar -y
sudo apt-get install php7.2-posix -y
sudo apt-get install php7.2-pspell -y
sudo apt-get install php7.2-readline -y
sudo apt-get install php7.2-shmop -y
sudo apt-get install php7.2-simplexml -y
sudo apt-get install php7.2-soap -y
sudo apt-get install php7.2-sockets -y
sudo apt-get install php7.2-sqlite3 -y
sudo apt-get install php7.2-sysvmsg -y
sudo apt-get install php7.2-sysvsem -y
sudo apt-get install php7.2-sysvshm -y
sudo apt-get install php7.2-wddx -y
sudo apt-get install php7.2-xml -y
sudo apt-get install php7.2-xsl -y
sudo apt-get install php7.2-recode -y
sudo apt-get install php7.2-dba -y
sudo apt-get install php7.2-imap -y
sudo apt-get install php7.2-interbase -y
sudo apt-get install php7.2-odbc -y
sudo apt-get install php7.2-pgsql -y
sudo apt-get install php7.2-tidy -y
sudo apt-get install php7.2-zip -y